name = "buffalo"
description = "Secure Bootloader for STM32F4"
version = "0.1.0-dev"

authors = ["Daniel Proano"]
maintainers = ["Daniel Proano <daniel.proano@yahoo.com>"]
licenses = "GPL-3.0-or-later"
website = "dannyproano.com"
tags = ["secure", "bootloader", "buffalo", "autonomous", "drone", "stm32f4"]

project-files = ["buffalo.gpr"]
executables = ["buffalo"]

[[
depends-on
]]
gnat_arm_elf = "15^"
